<?php
namespace App\Traits;

use App\Models\Author;
trait AuthorTrait{
    public function storeAuthors(){
        $authors = $this->getAuthors();
        foreach($authors as $author){
            Author::create($author);
        }
    }
    public function getAuthors(){
        return [
            ['name' => 'Muhammad Tahir Alkardi'],
            ['name' => 'Kamran Azam Sohdarvi'],
            ['name' => 'Samina Shehzad'],
            ['name' => 'Ali Hamza Qayum'],
            ['name' => 'Paulo Coelho'],
            ['name' => 'Touseef Ahmad Khan'],
            ['name' => 'Yasir Jawad'],
            ['name' => 'Yvonne Ridley'],
            ['name' => 'Philip K. Hitti'],
            ['name' => 'C_J_S Thomson'],
            ['name' => 'Ata-ui-Haq Qasmi'],
            ['name' => 'Qaisar Abbas Sabir'],
            ['name' => 'Michael H. Hart'],
            ['name' => 'Kautilya Chanakya'],
            ['name' => 'Aslam Rahi M.A'],
            ['name' => 'Robert T. Kiyosaki'],
            ['name' => 'Jay Shetty'],
            ['name' => 'David Schwartz, Phd'],
            ['name' => 'Shiv Khera'],
            ['name' => 'Napoleon Hill'],
            ['name' => 'Dale Carnegie'],
            ['name' => 'James Clear'],
            ['name' => 'Stephen R. Covey'],
            ['name' => 'Rachel Bridge'],
            ['name' => 'Cal Newport'],
            ['name' => 'Harold Lamb'],
            ['name' => 'Mobeen Rasheed'],
            ['name' => 'Mohammad Asim Azami'],
            ['name' => 'Doctor Muhammad Uzair'],
            ['name' => 'kalkar Ninja Kanoongo'],
            ['name' => 'Shahida Lateef'],
            ['name' => 'Al Imam-ul-Muhadis Sham-u-din'],
            ['name' => 'Molana Abdul Haleem Shara'],
            ['name' => 'Sadiq Hussain Sadiqi'],
            ['name' => 'Molvi Hammad Ali Saddiqi'],
            ['name' => 'Molana Abu Al Kalam Azad'],
            ['name' => 'Molana Waheed-ui-Din Khan'],
            ['name' => 'Al Hafiz-ul-Qadri'],
            ['name' => 'Abid Gondal'],
            ['name' => 'Shahid Ayoub'],
            ['name' => 'Amar Dehlvi'],
            ['name' => 'Munazza Hashmi'],
            ['name' => 'Nusrat Naseem'],
            ['name' => 'john Rose'],
            ['name' => 'Robin Sharma'],
            ['name' => 'Aflatoon'],
            ['name' => 'Asmat Chugtai'],
            ['name' => 'Abdul Waris Sajjid'],
            ['name' => 'Ziyaullah-al-Salfi'],
            ['name' => 'Adrees Zaqi Dehdera'],
            ['name' => 'Shiekh Abdul Qadir Jelani'],
            ['name' => 'Naveed Islam'],
            ['name' => 'Ahmad Shah Patras Bukhari'],
            ['name' => 'Leo Tolstoy'],
            ['name' => 'Shayan Aziz'],
            ['name' => 'Zabiullah Saddiuqi Balgan'],
            ['name' => 'Saleem Ahmad saddiuqi'],
            ['name' => 'Shoaib Ali Syed'],
            ['name' => 'Imran Shanawar'],
            ['name' => 'Ryan Holiday'],
            ['name' => 'Barack Obama'],
            ['name' => 'Mark Manson'],
            ['name' => 'Jonathan King'],
            ['name' => 'Elizabeth Gilbert'],
            ['name' => 'Paula Hawkins'],
            ['name' => 'Sun TZU'],
            ['name' => 'Ghulam Ali'],
            ['name' => 'Austin kleon'],
            ['name' => 'Hector Garcia'],
            ['name' => 'Francesc Miralles'],
            ['name' => 'Robert Maurer'],
            ['name' => 'Cynthia Covey haller'],
            ['name' => 'Reza Aslan'],
            ['name' => 'Partick Cockburn'],
            ['name' => 'James Wynbrandt'],
            ['name' => 'Ira Rifkin'],
            ['name' => 'Steven Levitsky'],
            ['name' => 'Daniel Ziblatt'],
            ['name' => 'Graeme Wood'],
            ['name' => 'Tim Marshall'],
            ['name' => 'Jim Kwik'],
            ['name' => 'George F. Nafizigar'],
            ['name' => 'Mark Walton'],
            ['name' => 'Steve Coll'],
            ['name' => 'Stephen M. R. Covery'],
            ['name' => 'Hector Garcia'],
            ['name' => 'Francesc Miralles'],
            ['name' => 'Edward De Bono'],
            ['name' => 'Gary Vaynerchuk'],
            ['name' => 'Maulana Wahiduddin Khan'],
            ['name' => 'Richard Templar'],
            ['name' => 'Mary L. Trump,PH.D.'],
            ['name' => 'Madiha Afzal'],
            ['name' => 'Christophe Jaffrelot'],
            ['name' => 'Saima Qureshi'],
            ['name' => 'Rima Noor Rizwan'],
            ['name' => 'J.M Thompson'],
            ['name' => 'Abdul Rasheed Iraqi'],
            ['name' => ' Nimra Ahmad'],
            ['name' => 'Nazia Kanwal Nazi'],
            ['name' => 'Qayyum Niazi'],
            ['name' => 'Umera Ahmad'],
            ['name' => 'Mubeen ghaznavi'],
            ['name' => 'Iqbal Bano'],
            ['name' => 'S,M Zafar'],
            ['name' => 'Kausar Niazi'],
            ['name' => 'Mujahid Lahori'],
            ['name' => 'Rizwan Abbas'],
            ['name' => 'Muhammad Mateen Khalid'],
            ['name' => 'Shiekh Muhammad Hiyat M.A'],
            ['name' => 'Saadat Hasan Manto'],
            ['name' => 'Khan Bahadur Maulvi Muhammad Hussain Sahib M.A'],
            ['name' => 'Syed Sabahuddin Abdur Rahman'],
            ['name' => 'Banarsi Prasad Saxena'],
            ['name' => 'Sadiq Hussain Siddiqui'],
            ['name' => 'Raees Ahmed Jafri'],
            ['name' => 'Inayat Ullah'],
            ['name' => 'Mim Aliff'],
            ['name' => 'Gumnaam Khatoon'],
            ['name' => 'Noor Ahmed Qaim Khani'],
            ['name' => 'Masood Mufti'],
            ['name' => 'Zahid Malik'],
            ['name' => 'Rabat T.O Saqi'],
            ['name' => 'Raja Yasir Nawaz'],
            ['name' => 'Beni Prasad'],
            ['name' => 'Dr Obaidullah Fahad Falahi'],
            ['name' => 'Muhammad Ilyas'],
            ['name' => 'S.M Zafar'],
            ['name' => 'Maulana Muhammad Ali Khan Sahib Arshi'],
            ['name' => 'Qaisar Chohan'],
            ['name' => 'Sardar Ji Singh'],
            ['name' => 'Saleem Gilani'],
            ['name' => 'Muhammad Nawaz Merani'],
            ['name' => 'Toseef Aslam'],
            ['name' => 'Kashan Parshad Kol'],
            ['name' => 'Sundas Jabeen'],
            ['name' => 'Khawaja Hassan Nizami'],
            ['name' => 'Dr Robert H Schuller'],
            ['name' => 'Arif Shabeer'],
            ['name' => 'Amrita Pritam'],
            ['name' => 'Ishtiaq Ahmed'],
            ['name' => 'Muhammad Kashif Mohal'],
            ['name' => 'Muhammad Sharif Baqa'],
            ['name' => 'Aziz Ahmed'],
            ['name' => 'Professor Gyan Chand Jain'],
            ['name' => 'Dr Khalifa Abdul Hakim'],
            ['name' => 'Abu Aleeha'],
            ['name' => 'Muhhammad Inayatullah Subhani'],
            ['name' => 'Robina Naz'],
            ['name' => 'Mah Jabeen'],
            ['name' => 'Gunda Singh'],
            ['name' => 'Ghulam Rasool Mehar'],
            ['name' => 'Abdul Hameed Salaq'],
            ['name' => 'Almas M.A'],
            ['name' => 'Dr Hashmat jah'],
            ['name' => 'Zia Uddin Lahori'],
            ['name' => 'Dr Sayed Akhtar Jafri'],
            ['name' => 'K.L Gaba'],
            ['name' => 'Professor Ahmed Uddin Marharvi'],
            ['name' => 'Maulana Muhammad Jafar Thanesari'],
            ['name' => 'Rachal Bridge'],
            ['name' => 'A.P.J Abdul Kalam'],
            ['name' => 'Wasif Ali Wasif'],
            ['name' => 'Fars Mughal'],
            ['name' => 'Tayyaba Hashmi'],
            ['name' => 'Jehangir Bader'],
        ];
    }
}





?>
